EMAIL = 'xl'
PASSWORD = 'mlr'
SECRET_KEY = 'ajfkjekjfakjj2ksjka'
SQLALCHEMY_DATABASE_URI = 'postgresql://xl:123456@192.168.19.130/testdb'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
BCRYPT_LOG_ROUNDS = 8
